spring:
  datasource:
    url: jdbc:h2:mem:teste
    username: dev
    password: 
    driverClassName: org.h2.Driver
  
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
  
  h2:
    console:
        enabled: true
        path: /h2